#!/bin/bash

# This is a slightly different deploy script because it doesn't do any actual
# etl processing, or uploading.  It builds a wiki based on other competitions.

COMPETITION="GlobalView"
LFC_DIR=`dirname "${0}"`
BASE_DATA_DIR="${1}"

if [ "${BASE_DATA_DIR}" = "" ]; then
  echo "ERROR: BASE_DATA_DIRECTORY argument required."
  echo ""
  echo "Usage: '${0} BASE_DATA_DIRECTORY'"
  echo ""
  echo "Competitions are looked for in BASE_DATA_DIRECTORY"
  echo ""
  exit 1
fi

DATA_DIR="${BASE_DATA_DIR}/${COMPETITION}"

# Make sure we have python3
python3 -V > /dev/null 2>&1 || { echo "python3 required, aborting" ; exit 1; }

COMPETITIONS="EO2020 100Change2020 100Change2017 LLIIA2020 RacialEquity2030 Climate2030 ECW2020 LoneStar2020"
TDC_CONFIG_DIR="${DATA_DIR}/tdcconfig"
RUNNER="${LFC_DIR}"/populate-wiki

COMPETITIONS_ARGUMENT=""
for comp in $COMPETITIONS ; do
  FILE="$BASE_DATA_DIR/$comp/tdcconfig/etl-processed.csv"
  if [ ! -f $FILE ] ; then
    echo "Error: $FILE does not seem to be there, probably need to run the ./deploy in torque-sites/$comp/etl with -c option"
    exit 1
  fi
  COMPETITIONS_ARGUMENT="$COMPETITIONS_ARGUMENT --competition=$comp --competition-csv=$FILE"
done

echo "Populating wiki..."
mkdir -p ${TDC_CONFIG_DIR}
$RUNNER \
  --tdc-config-dir="${TDC_CONFIG_DIR}" \
  $COMPETITIONS_ARGUMENT
echo "Done."
