allowlist = {
    "Application": [
        "GUID",
        "Competition Domain",
        "Application #",
        "Admin Review Status",
        "Participant",
        "Legal Name",
        "Self-Identification",
        "Organization Name",
        "Organization Location",
        "Primary Contact",
        "Secondary Contact",
        "Organization Legal Status",
        "Organizational Demographics",
        "Source",
        "Project Title",
        "Project Description",
        "Executive Summary",
        "Video",
        "Organization Website",
        "Project Website",
        "Primary Area of Expertise",
        "Team Collaboration",
        "Case for Partnership",
        "Key Partner #1",
        "Key Partner #2",
        "Key Partner #3",
        "Key Partner #4",
        "Key Partner #5",
        "Why Your Team",
        "Key Staff #1",
        "Key Staff #1 Affiliation",
        "Key Staff #1 Biography",
        "Key Staff #2",
        "Key Staff #2 Affiliation",
        "Key Staff #2 Biography",
        "Key Staff #3",
        "Key Staff #3 Affiliation",
        "Key Staff #3 Biography",
        "Challenge Statement",
        "Solution Overview",
        "Project Focus",
        "Community Engagement",
        "Local Context",
        "Theory of Change",
        "Innovation",
        "Opportunities and Accommodations",
        "COVID-19 Impact",
        "Priority Populations",
        "Diversity-Equity-Inclusion",
        "Primary Subject Area",
        "Primary Subject Area Category",
        "Key Words and Phrases",
        "Current Work #1 Location",
        "Current Work #2 Location",
        "Current Work #3 Location",
        "Current Work #4 Location",
        "Current Work #5 Location",
        "Future Work #1 Location",
        "Future Work #2 Location",
        "Future Work #3 Location",
        "Future Work #4 Location",
        "Future Work #5 Location",
        "Sustainable Development Goals",
        "Evidence of Effectiveness",
        "Ability To Scale",
        "Timeline and Milestones",
        "Measurement of Results",
        "Barrier Assessment and Risk Mitigation",
        "Bibliography",
        "Other Considerations",
        "Total Projected Costs",
        "Budget Narrative",
        "Budget Data",
        "Budget Notes",
        "Total Resource Requirements",
        "Charitable Purpose",
        "Private Benefit",
        "Lobbying Activities",
        "Human Subject Research",
        "Intellectual Property",
        "Applicant Organization Identification Authority",
        "Applicant Tax Identification Number",
        "Annual Operating Budget",
        "Number of Employees",
        "Attachments",
        "MediaWiki Title",
        "GlobalView MediaWiki Title",
        "Competition Name",
        "Funder #1",
        "Funder #1: First Year of Funding",
        "Funder #1: Last Year of Funding",
        "Funder #1: Amount of Funding",
        "Funder #2",
        "Funder #2: First Year of Funding",
        "Funder #2: Last Year of Funding",
        "Funder #2: Amount of Funding",
        "Funder #3",
        "Funder #3: First Year of Funding",
        "Funder #3: Last Year of Funding",
        "Funder #3: Amount of Funding",
        "Achievement Level",
    ],
    "PeerToPeer": [
        "Peer ACTIONABLE Judge Data",
        "Peer ACTIONABLE Score Normalized",
        "Peer BOLD Judge Data",
        "Peer BOLD Score Normalized",
        "Peer COMMUNITY-INFORMED Judge Data",
        "Peer COMMUNITY-INFORMED Score Normalized",
        "Peer DURABLE Judge Data",
        "Peer DURABLE Score Normalized",
        "Peer EQUITABLE Judge Data",
        "Peer EQUITABLE Score Normalized",
        "Peer EVIDENCE-BASED Judge Data",
        "Peer EVIDENCE-BASED Score Normalized",
        "Peer FEASIBLE Judge Data",
        "Peer FEASIBLE Score Normalized",
        "Peer IMPACTFUL Judge Data",
        "Peer IMPACTFUL Score Normalized",
        "Peer INNOVATIVE Judge Data",
        "Peer INNOVATIVE Score Normalized",
        "Peer SCALABLE Judge Data",
        "Peer SCALABLE Score Normalized",
        "Peer TRANSFORMATIVE Judge Data",
        "Peer TRANSFORMATIVE Score Normalized",
    ],
    "Panel": [
        "Panel ACTIONABLE Judge Data",
        "Panel ACTIONABLE Score Normalized",
        "Panel BOLD Judge Data",
        "Panel BOLD Score Normalized",
        "Panel COMMUNITY-INFORMED Judge Data",
        "Panel COMMUNITY-INFORMED Score Normalized",
        "Panel DURABLE Judge Data",
        "Panel DURABLE Score Normalized",
        "Panel EQUITABLE Judge Data",
        "Panel EQUITABLE Score Normalized",
        "Panel EVIDENCE-BASED Judge Data",
        "Panel EVIDENCE-BASED Score Normalized",
        "Panel FEASIBLE Judge Data",
        "Panel FEASIBLE Score Normalized",
        "Panel IMPACTFUL Judge Data",
        "Panel IMPACTFUL Score Normalized",
        "Panel INNOVATIVE Judge Data",
        "Panel INNOVATIVE Score Normalized",
        "Panel SCALABLE Judge Data",
        "Panel SCALABLE Score Normalized",
        "Panel TRANSFORMATIVE Judge Data",
        "Panel TRANSFORMATIVE Score Normalized",
    ],
    "Confidential": [
        "Peer Overall Score Rank Normalized",
        "Peer Sum of Scores Normalized",
        "Panel Overall Score Rank Normalized",
        "Panel Sum of Scores Normalized",
        "Restricted Attachments",
    ],
    "Analysis": [
        "LFC Analysis",
        "LFC Financial Data",
    ],
}
