#!/bin/bash

# Copyright (C) 2017, 2019, 2020  Open Tech Strategies, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

CSV_ONLY=""
PARE=""
GPG_PASSPHRASE=""
while getopts "cp:g:" opt; do
  case $opt in
    c) CSV_ONLY="--csv-only" ;;
    p) PARE="--pare=$OPTARG" ;;
    g) GPG_PASSPHRASE="$OPTARG" ;;
  esac
done
shift $((OPTIND -1))

BASE_DATA_DIR="${1}"
if [ "${BASE_DATA_DIR}" = "" ]; then
  echo "ERROR: BASE_DATA_DIRECTORY argument required."
  echo ""
  echo "Usage: '${0} [-c] [-p arg] BASE_DATA_DIRECTORY'"
  echo ""
  echo "Options:"
  echo ""
  echo "  -c                  Uploads CSV only.  Skips creating pages and"
  echo "                      uploading attachments."
  echo "  -p <arg>            If ARG is a number, pares by factor of ARG. If"
  echo "                      ARG begins with +, then ARG is a comma separated"
  echo "                      list of keys to include.  If ARG begins with @,"
  echo "                      then ARG is a file with a newline separated list"
  echo "                      of keys to include."
  echo "  -g <arg>            Accepts a GPG symmetric passphrase to use when decrypting."
  echo ""
  exit 1
fi
