#!/bin/bash

# Copyright (C) 2017, 2019, 2020  Open Tech Strategies, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

decrypt () {
	local output_location="${1}"
	local encrypted_location="${2}"
	local passphrase="${3}"

	if [ -z "${passphrase}" ]; then
		if command -v opass &> /dev/null ; then
			echo 'Attempting to get PASSPHRASE from opass'
			passphrase=$(opass show clients/lever-for-change/data-encryption-key | tail -n 1)

			# This line depends a bit on some assumptions about how the caller is using
			# variables set up in the ./init file
			GPG_PASSPHRASE=$passphrase
		fi
	fi

	if [ -z "${passphrase}" ]; then
		echo 'NO PASSPHRASE'
		gpg -o "${output_location}" --decrypt "${encrypted_location}" || exit 1
	else
		echo 'PASSPHRASE'
		gpg --batch --passphrase "${passphrase}" -o "${output_location}" --decrypt "${encrypted_location}" || exit 1
	fi
}
