#!/bin/bash

# Copyright (C) 2017, 2019, 2020  Open Tech Strategies, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

COMPETITION="LLIIA2020"
LFC_DIR=`dirname "${0}"`
BASE_DATA_DIR="${1}"

if [ "${BASE_DATA_DIR}" = "" ]; then
  echo "ERROR: BASE_DATA_DIRECTORY argument required."
  echo ""
  echo "Usage: '${0} BASE_DATA_DIRECTORY'"
  echo ""
  echo "BASE_DATA_DIRECTORY/LLIIA2020 is where all the work is done."
  echo ""
  exit 1
fi

DATA_DIR="${BASE_DATA_DIR}/${COMPETITION}"

# Make sure we have python3
python3 -V > /dev/null 2>&1 || { echo "python3 required, aborting" ; exit 1; }

PROPOSALS_CSV="LLIIAE_registration_and_application_data.csv"
BASE_ATTACHMENTS="LLIAE_registration_and_application_data.zip"
ATTACHMENTS_DIR="${DATA_DIR}/attachments/"
JUDGE_EVALUATION_CSV="LLIIA_Peer_Review_Data_Pseudonymous_20200803.csv"
ADMIN_REVIEW_CSV="AdminReviewP2P_LLIIA2020_07082020.csv"
PANEL_EVALUATION_CSV="LLIIA_Evaluation_Panel_Data_anon.csv"
BUDGET_ZIP="LLIAE_AR_budget_data.zip"
BUDGET_CSV="LLIAE_registration_and_application_export_budget_data.csv"
REGIONCONFIG_CSV="regionconfig.csv"
TOP16_DATA_FILE="top16.dat"
TMP_ATTACHMENTS_DIR="${DATA_DIR}/tmpattachments"

TDC_CONFIG_DIR="${DATA_DIR}/tdcconfig"
RUNNER="${LFC_DIR}"/compose-and-upload

if [ ! -d "${DATA_DIR}" ] ; then
  echo "Stage 0: Setting up data directory..."

  if [ "${OTS_DIR}" = "" ] ; then
    echo "ERROR: \$OTS_DIR is not set up"
    echo ""
    echo "See bureaucracy/onboarding about setting the OTS_DIR environment variable up"
    exit 1
  fi

  ENCRYPTED_DIR="${OTS_DIR}/clients/lever-for-change/torque-sites/${COMPETITION}/data/bigdata"
  if [ ! -d "${ENCRYPTED_DIR}" ] ; then
    echo "ERROR: it looks like your encrypted dir isn't checked out"
    echo ""
    echo "It was expected to be in:"
    echo "  $ENCRYPTED_DIR"
    echo ""
    echo "You will need to check out the subversion torque-sites data, and then"
    echo "run get-bigdata from ${OTS_DIR}/clients/lever-for-change/torque-sites/${COMPETITION}/data/"
    exit 1
  fi

  mkdir -p $DATA_DIR
  echo "Decrypting..."

  gpg -o ${DATA_DIR}/${ADMIN_REVIEW_CSV} --decrypt ${ENCRYPTED_DIR}/${ADMIN_REVIEW_CSV}.gpg || exit 1
  gpg -o ${DATA_DIR}/${JUDGE_EVALUATION_CSV} --decrypt ${ENCRYPTED_DIR}/${JUDGE_EVALUATION_CSV}.gpg || exit 1
  gpg -o ${DATA_DIR}/${TOP16_DATA_FILE} --decrypt ${ENCRYPTED_DIR}/${TOP16_DATA_FILE}.gpg || exit 1
  gpg -o ${DATA_DIR}/${PANEL_EVALUATION_CSV} --decrypt ${ENCRYPTED_DIR}/${PANEL_EVALUATION_CSV}.gpg || exit 1
  gpg -o ${DATA_DIR}/${BASE_ATTACHMENTS} --decrypt ${ENCRYPTED_DIR}/${BASE_ATTACHMENTS}.gpg || exit 1
  gpg -o ${DATA_DIR}/${BUDGET_ZIP} --decrypt ${ENCRYPTED_DIR}/${BUDGET_ZIP}.gpg || exit 1

  unzip -d ${DATA_DIR} ${DATA_DIR}/${BUDGET_ZIP}

  mkdir -p ${TOC_DIR}
  mkdir -p ${TDC_CONFIG_DIR}

  echo "Setting up attachments..."
  unzip -d ${ATTACHMENTS_DIR} ${DATA_DIR}/${BASE_ATTACHMENTS}
  mv "${ATTACHMENTS_DIR}/LLIIAE_registration_and_application_data.csv" $DATA_DIR

  # Clean up large zips to save disk space
  rm ${DATA_DIR}/${BASE_ATTACHMENTS}
fi

if ! echo "831bd76551d1d21aea16820aa64463d27d3001a1  $DATA_DIR/$PROPOSALS_CSV" | sha1sum -c &> /dev/null ; then
  echo "ERROR: SHA of PROPOSALS_CSV did not match expectation!"
  echo "This means that we most likely got a new file, which may have the old"
  echo "errors in it (specifically the organization proposal 829)."
  echo "If we got a new file and there are no further errors, you"
  echo "can remove this check from torque-refresh!  If not, please"
  echo "make adjustments in a new file and update the sha."
  exit 1
fi


mkdir -p $TDC_CONFIG_DIR

${RUNNER} --proposals-csv="${DATA_DIR}/${PROPOSALS_CSV}" \
          --admin-review-csv="${DATA_DIR}/${ADMIN_REVIEW_CSV}" \
          --judge-evaluation-csv="${DATA_DIR}/${JUDGE_EVALUATION_CSV}" \
          --panel-evaluation-csv="${DATA_DIR}/${PANEL_EVALUATION_CSV}" \
          --budget-csv="${DATA_DIR}/${BUDGET_CSV}" \
          --top16-data-file="${DATA_DIR}/${TOP16_DATA_FILE}" \
          --attachments-dir=${ATTACHMENTS_DIR} \
          --tdc-config-dir="${TDC_CONFIG_DIR}"
if [ $? -ne 0 ]; then
		echo Failure!
		exit 1
fi

echo "Done creating wiki."
