#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2017, 2019, 2020 Open Tech Strategies, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

__doc__ = """\
Compose all of the Lever for Change 2020 EO CSV files.

Usage:

  $ compose-csvs \\
       --proposals-csv=PROPOSALS_CSV \\
       --admin-review-csv=ADMIN_REVIEW_CSV \\
       --judge-evaluation-csv=JUDGE_EVALUATION_CSV \\
       --regionconfig-csv=REGIONCONFIG_CSV \\
       --toc-dir=TOC_DIR \\
       --attachments-dir=ATTACHMENTS_DIR \\
       --tdc-config-dir=TDC_CONFIG_DIR \\
       --pare=PARE \\
       --collection-only

Command-line options:
  --proposals-csv FILE            FILE is a CSV file representing the bulk
                                  of the proposal information

  --admin-review-csv FILE         FILE is a CSV file representing which applications
                                  in PROPOSALS_CSV should be included

  --judge-evaluation-csv FILE     FILE is a CSV file with a many to one relationshp
                                  between judges and the proposals they evaluated,
                                  with the extra data being their evaluation

  --lfc-evaluation-csv FILE       FILE is a CSV file with the LFC evaluation data,
                                  keyed by application #.

  --thematic-areas-csv FILE       FILE is a CSV file with thematic areas declared by
                                  LFC for more user friendly groupings.

  --bridgespan-data-csv FILE      FILE is a CSV file with extra data, provided by bridgespan.

  --bridgespan-overview-folder D  D is the directory with the financial overview spreadsheets
                                  for the bridgespan data.

  --regionconfig-csv FILE         FILE is a csv of country/subregion/region
                                  configurations, that when provided, allows a detailed
                                  geographic TOC to be created

  --attachments-dir DIR           DIR is a directory for compose-csvs to look in for what attachments
                                  will be uploaded to the torque wiki.  It needs to have subdirectories
                                  by proposal number.

  --tdc-config-dir DIR            DIR is the location for files that are the base configuration files
                                  needed by TorqueDataConnect, and can be optionally, manually, put on
                                  the torque wiki.  We don't automatically do that because we want to
                                  overwrite the configuration out there.

  --pare ARG                      If ARG is a number, reduce the number of items to 1/ARG.  If
                                  ARG begins with +, then ARG is a comma separated list of
                                  keys to include.  If ARG begins with @, then ARG is a
                                  file with a list of keys to include.  For both + and @,
                                  the list of keys will be limited to only the ones provided.

  --csv-only                      Only upload the created CSV file.  Don't upload attachments or
                                  create wiki pages.  For use to speed up process when wiki has been
                                  created already.
"""

from etl import competition, wiki, toc, tdc, utils
import config
import getopt
import sys
import os
import csv
import re
import json


class ThematicAreasAdder(competition.InformationAdder):
    """Adds the thematic area to proposals"""

    def __init__(self, csv_location):
        self.data = {}
        if csv_location is None:
            return

        csv_reader = csv.reader(
            open(csv_location, encoding="utf-8"), delimiter=",", quotechar='"'
        )

        header = next(csv_reader)
        app_col = header.index("Review #")
        thematic_area_col = header.index("Thematic Area")
        for row in csv_reader:
            self.data[row[app_col]] = row[thematic_area_col]

    def column_names(self):
        return ["Thematic Area"]

    def cell(self, proposal, column_name):
        if proposal.key() in self.data:
            return self.data[proposal.key()]

        return ""


class BridgeSpanDataAdder(competition.InformationAdder):
    """Adds and processes the BridgeSpan data"""

    def __init__(self, csv_location, overview_folder):
        """Takes a CSV_ representing a csv with the first column being
        a review number, and the rest being other infromation provided.

        OVERVIEW_FOLDER is where supporting budget csvs can be found."""

        self.data = {}
        if csv_location is None:
            return

        csv_reader = csv.reader(
            open(csv_location, encoding="utf-8"), delimiter=",", quotechar='"'
        )

        keys = next(csv_reader)
        for row in csv_reader:
            self.data[row[0]] = {
                key: self.fix_bridgespan_cell(cell) for (key, cell) in zip(keys, row)
            }
            self.data[row[0]][
                "Financial overview table"
            ] = self.process_bridgespan_financial_overview(overview_folder, row[0])

    def process_bridgespan_financial_overview(
        self, overview_folder, application_number
    ):
        """Takes an OVERVIEW_FOLDER and APPLICATION_NUMBER to find a financial
        overview csv, then uses the data therein to make an object to display on
        the final table.  This object is specific to the data being passed in,
        and so may break if the data changes.  That's unlikely, though.

        For instance, it assumes 5 years (2014-2018), and rows."""

        reader = csv.reader(
            open(
                os.path.join(
                    overview_folder, application_number + "-financial-overview.csv"
                ),
                encoding="mac_roman",
            ),
            delimiter=",",
            quotechar='"',
        )

        table = {"rows": []}

        # Header line is always the same, so we'll put in template
        next(reader)

        for row in reader:
            if row[0].startswith("Magnitude of surplus"):
                table["Magnitude of surplus"] = row[1]
                continue

            row_obj = {}
            row_obj["name"] = row[0]
            row_obj["data"] = []

            for col in row[1:6]:
                row_obj["data"].append(col)
            table["rows"].append(row_obj)

        return table

    def fix_bridgespan_cell(self, cell):
        """Uses FIX_CELL to fix CELL, then does additional fixing based
        on the specifics of the bridgespan data.  Then returns the fixed
        cell."""

        cell = utils.fix_cell(cell)

        # Bridgespan comes with a second bullet type for sublists (the circle type)
        subbullets_re = re.compile("^◦", re.MULTILINE)
        cell = subbullets_re.sub("**", cell)

        # Make the first line bold if it ends with a colon
        bold_first_re = re.compile("^(\*+) ([^.,:\n]*:)", re.MULTILINE)
        cell = bold_first_re.sub("\\1 '''\\2'''", cell)

        return cell

    def column_names(self):
        return ["LFC Analysis"]

    def cell(self, proposal, column_name):
        if proposal.key() in self.data:
            return self.data[proposal.key()]


class LFCEvaluationAdder(competition.InformationAdder):
    """Adds the result of the LFC Evaluation (A spreadsheet created by OTS).
    Adds it on to the result of the bridge span analysis above."""

    def __init__(self, csv_location):
        csv_reader = csv.reader(
            open(csv_location, encoding="utf-8"), delimiter=",", quotechar='"'
        )
        next(csv_reader)
        self.data = {row[0]: row[1] for row in csv_reader}

    def column_names(self):
        return ["LFC Analysis"]

    def cell(self, proposal, column_name):
        if proposal.key() in self.data:
            if proposal.cell("LFC Analysis"):
                retn = proposal.cell("LFC Analysis")
            else:
                retn = {}

            retn["Recommendation"] = self.data[proposal.key()]
            return retn
        else:
            return proposal.cell("LFC Analysis")


def main():
    """Compose the LFC input and emit it as html-ized csv."""
    try:
        opts, args = getopt.getopt(
            sys.argv[1:],
            "",
            [
                "proposals-csv=",
                "admin-review-csv=",
                "judge-evaluation-csv=",
                "lfc-evaluation-csv=",
                "thematic-areas-csv=",
                "bridgespan-data-csv=",
                "bridgespan-overview-folder=",
                "regionconfig-csv=",
                "top13-data-file=",
                "tdc-config-dir=",
                "attachments-dir=",
                "pare=",
                "collection-only",
            ],
        )
    except getopt.GetoptError as err:
        sys.stderr.write("ERROR: '%s'\n" % err)
        sys.exit(2)

    proposals_csv = None
    admin_review_csv = None
    thematic_areas_csv = None
    bridgespan_data_csv = None
    bridgespan_overview_folder = None
    regionconfig_csv = None
    top13_data_file = None
    attachments_dir = None
    tdc_config_dir = None
    pare = None
    collection_only = False
    for o, a in opts:
        if o == "--proposals-csv":
            proposals_csv = a
        elif o == "--pare":
            pare = a
        elif o == "--collection-only":
            collection_only = True
        elif o == "--admin-review-csv":
            admin_review_csv = a
        elif o == "--judge-evaluation-csv":
            judge_evaluation_csv = a
        elif o == "--lfc-evaluation-csv":
            lfc_evaluation_csv = a
        elif o == "--thematic-areas-csv":
            thematic_areas_csv = a
        elif o == "--bridgespan-data-csv":
            bridgespan_data_csv = a
        elif o == "--bridgespan-overview-folder":
            bridgespan_overview_folder = a
        elif o == "--regionconfig-csv":
            regionconfig_csv = a
        elif o == "--top13-data-file":
            top13_data_file = a
        elif o == "--tdc-config-dir":
            tdc_config_dir = a
        elif o == "--attachments-dir":
            attachments_dir = a
        else:
            sys.stderr.write("ERROR: unrecognized option '%s'\n" % o)
            sys.exit(2)

    if proposals_csv is None:
        sys.stderr.write("ERROR: need --proposals-csv option.\n\n")
        sys.stderr.write(__doc__)
        sys.exit(1)

    comp = competition.CsvBasedCompetition(
        proposals_csv, "EO2020", "Application #", pare
    )
    comp.add_supplemental_information(competition.MediaWikiTitleAdder("Project Title"))
    comp.add_supplemental_information(
        competition.GlobalViewMediaWikiTitleAdder("EO2020", "Project Title")
    )
    comp.add_supplemental_information(
        competition.StaticColumnAdder("Competition Name", "EO2020")
    )
    comp.add_supplemental_information(
        competition.StaticColumnAdder("Achievement Level", "")
    )
    comp.add_supplemental_information(
        competition.StaticColumnAdder("Total Projected Costs", 10000000)
    )
    comp.add_supplemental_information(
        competition.StaticColumnAdder(
            "Sustainable Development Goals",
            [{"number": 8, "title": "Decent Work and Economic Growth" }]
        )
    )

    fix_cell_processor = competition.FixCellProcessor()
    comp.process_all_cells_special(fix_cell_processor)
    fix_cell_processor.report()

    attachments = competition.RegexSpecifiedAttachments(
        comp.sorted_proposal_keys, attachments_dir
    )
    comp.process_cells_special(
        "Annual Operating Budget",
        competition.AnnualBudgetProcessor(
            {
                competition.AnnualBudget.LESS_THAN_1_MIL: "Less than $1 Million",
                competition.AnnualBudget.BETWEEN_1_MIL_AND_5_MIL: "$1 to 5 Million",
                competition.AnnualBudget.BETWEEN_5_MIL_AND_10_MIL: "&gt;$5 to 10 Million",
                competition.AnnualBudget.BETWEEN_10_MIL_AND_25_MIL: "&gt;$10 to 25 Million",
                competition.AnnualBudget.BETWEEN_25_MIL_AND_50_MIL: "&gt;$25 to 50 Million",
                competition.AnnualBudget.BETWEEN_50_MIL_AND_100_MIL: "&gt;$50 to 100 Million",
                competition.AnnualBudget.BETWEEN_100_MIL_AND_500_MIL: "&gt;$100 to 500 Million",
                competition.AnnualBudget.BETWEEN_500_MIL_AND_1_BIL: "",
                competition.AnnualBudget.MORE_THAN_1_BIL: "&gt;$1 Billion",
            }
        ),
    )
    comp.process_cells_special(
        "Primary Subject Area",
        competition.PrimarySubjectAreaProcessor()
    )

    attachments.specify_new_subcolumn(
        ".*Finalist Memo.*", "Finalist Memo Attachment", 1
    )
    attachments.specify_new_subcolumn(
        ".*Technical Review.*", "Technical Review Attachment", 2
    )
    attachments.specify_new_subcolumn(
        ".*Site Visit Notes.*", "Site Visit Notes Attachment", 3
    )
    attachments.specify_new_subcolumn(
        ".*Financial Review.*", "Financial Review Attachment", 4
    )
    attachments.specify_new_subcolumn(".*DEI Review.*", "DEI Review Attachment", 5)
    attachments.specify_new_subcolumn(
        ".*Accessibility Review.*", "Accessibility Review Attachment", 6
    )
    attachments.specify_new_subcolumn(".*Prospectus.*", "Prospectus Attachment", 7)
    attachments.specify_by_regex(".*Synthesis Memo", "Synthesis Memo", 8)
    attachments.specify_by_regex(".*Supplemental Documents", "Financials and MoUs", 9)
    attachments.specify_by_regex(
        ".*Response to Questions", "Responses to Follow Up Questions", 10
    )
    comp.add_supplemental_information(attachments)

    if judge_evaluation_csv is not None:
        comp.add_supplemental_information(
            competition.EvaluationAdder(
                "Panel",
                judge_evaluation_csv,
                app_col_name="Application #",
                score_rank_raw_col_name="OverallScoreRank",
                score_rank_normalized_col_name="OverallScoreRankNormalized",
                sum_of_scores_raw_col_name="SumOfScores",
                sum_of_scores_normalized_col_name="SumOfScoresNormalized",
                trait_col_name="Trait",
                score_raw_col_name="TraitScore",
                score_normalized_col_name="TraitScoreNormalized",
                comments_col_name="TraitJudgeComment",
                comments_score_raw_col_name="TraitScore",
                comments_score_normalized_col_name="TraitScoreNormalized",
                anonymous_judge_name_col_name="AnonymousJudgeName",
                primary_rank=True,
            )
        )

    for old, new in zip(
        [
            "Likelihood of Success",
            "Magnitude of Impact",
            "Potential for Scale",
            "Strength of Evidence",
        ],
        ["DURABLE", "IMPACTFUL", "SCALABLE", "EVIDENCE-BASED"],
    ):
        comp.transform_sheet(
            competition.ColumnRenamer(
                "Panel %s Score" % old,
                "Panel %s Score" % new,
            )
        )
        comp.transform_sheet(
            competition.ColumnRenamer(
                "Panel %s Judge Data" % old,
                "Panel %s Judge Data" % new,
            )
        )

    comp.add_supplemental_information(ThematicAreasAdder(thematic_areas_csv))
    comp.add_supplemental_information(
        BridgeSpanDataAdder(bridgespan_data_csv, bridgespan_overview_folder)
    )
    comp.add_supplemental_information(LFCEvaluationAdder(lfc_evaluation_csv))

    admin_review = competition.AdminReview(admin_review_csv, "Application #", "Status")
    comp.add_supplemental_information(admin_review)
    comp.filter_proposals(admin_review)

    comp.process_cells_special("Priority Populations", competition.ToListProcessor())

    comp.transform_sheet(
        competition.LocationCombiner(
            column_name="Organization Location",
            address_1="Street Address",
            address_2="Address Line 2",
            city="City",
            state="State / Province",
            locality="Locality / County / District",
            country="Nation",
            zip_postal="Zip / Postal Code",
        )
    )

    comp.transform_sheet(
        competition.PersonCombiner(
            column_name="Participant",
            first_name="Participant First Name",
            last_name="Participant Last Name",
            email="Participant email",
        )
    )
    comp.transform_sheet(
        competition.PersonCombiner(
            column_name="Primary Contact",
            first_name="Primary Contact First Name",
            last_name="Primary Contact Last Name",
            title="Primary Contact Title",
            phone="Primary Contact Phone",
            email="Primary Contact Email",
        )
    )
    comp.transform_sheet(
        competition.PersonCombiner(
            column_name="Secondary Contact",
            first_name="Secondary Contact First Name",
            last_name="Secondary Contact Last Name",
            title="Secondary Contact Title",
            phone="Secondary Contact Phone",
            email="Secondary Contact Email",
        )
    )
    for num in ["1", "2", "3"]:
        comp.transform_sheet(
            competition.PersonCombiner(
                column_name="Key Staff #%s" % num,
                first_name="Key Staff #%s First Name" % num,
                last_name="Key Staff #%s Last Name" % num,
            )
        )

    # This exists because one of them was not like the others, and it makes the loop below prettier
    comp.transform_sheet(
        competition.ColumnRenamer(
            "Location of Future Work #1 State / Province",
            "Location of Future Work #1 State /Province",
        )
    )
    for work_type in ["Current", "Future"]:
        for num in ["1", "2", "3", "4", "5"]:
            comp.transform_sheet(
                competition.LocationCombiner(
                    column_name="%s Work #%s Location" % (work_type, num),
                    state="Location of %s Work #%s State /Province" % (work_type, num),
                    country="Location of %s Work #%s Nation" % (work_type, num),
                    locality="Location of %s Work #%s Locality / District / County"
                    % (work_type, num),
                )
            )
            comp.remove_information(
                competition.ColumnRemover(
                    "Location of %s Work #%s Nation ID" % (work_type, num)
                )
            )
            comp.remove_information(
                competition.ColumnRemover(
                    "Location of %s Work #%s State / Province ID" % (work_type, num)
                )
            )
            comp.remove_information(
                competition.ColumnRemover(
                    "Location of %s Work #%s Locality / District / County ID"
                    % (work_type, num)
                )
            )

    comp.transform_sheet(
        competition.ColumnRenamer("EIN", "Applicant Tax Identification Number")
    )
    comp.transform_sheet(
        competition.ColumnRenamer("Ability to Scale", "Ability To Scale")
    )
    comp.transform_sheet(
        competition.ColumnRenamer("Legal Status", "Organization Legal Status")
    )
    comp.transform_sheet(
        competition.ColumnRenamer("Org Website", "Organization Website")
    )
    comp.transform_sheet(
        competition.ColumnRenamer(
            "Org Primary Area of Expertise", "Primary Area of Expertise"
        )
    )
    comp.transform_sheet(
        competition.ColumnRenamer("Org Collaboration", "Team Collaboration")
    )
    comp.transform_sheet(
        competition.ColumnRenamer("Key Words", "Key Words and Phrases")
    )
    comp.transform_sheet(
        competition.ColumnRenamer(
            "Timeline-Milestones-Measurement of Results", "Timeline and Milestones"
        )
    )
    comp.transform_sheet(
        competition.ColumnRenamer(
            "Barrier Assessment & Risk Mitigation",
            "Barrier Assessment and Risk Mitigation",
        )
    )
    comp.transform_sheet(
        competition.ColumnRenamer("Thematic Area", "Primary Subject Area Category")
    )

    comp.remove_information(competition.ColumnRemover("GUID + Competition Domain"))
    comp.remove_information(competition.ColumnRemover("Nation ID"))
    comp.remove_information(competition.ColumnRemover("State / Province ID"))
    comp.remove_information(
        competition.ColumnRemover("Locality / County / District ID")
    )
    comp.remove_information(competition.ColumnRemover("Priority Populations ID"))
    comp.remove_information(competition.ColumnRemover("Primary Subject Area ID"))
    comp.remove_information(
        competition.ColumnRemover("Org Primary Area of Expertise ID")
    )

    comp.sort("Rank", True)

    comp.add_toc(toc.GenericToc("Topic_TOC", "Primary Subject Area Category"))
    comp.add_toc(toc.GenericListToc("Population_TOC", "Priority Populations"))
    proposal_formatter = toc.WikiTableTocProposalFormatter(
        [
            {
                "name": "Organization Name",
                "heading": "Organization",
            },
            {
                "name": "Project Title",
                "heading": "Title",
                "link": True,
            },
            {
                "name": "Application #",
                "heading": "ID #",
                "right_aligned": True,
            },
            {
                "name": "Rank",
                "heading": "Rank",
                "right_aligned": True,
            },
        ]
    )
    all_proposals = toc.ListToc("AllProposals")
    all_proposals.proposal_formatter = proposal_formatter
    comp.add_toc(all_proposals)

    top25 = toc.ListToc("Top_25")
    top25.proposal_formatter = proposal_formatter
    top25.proposals = comp.ordered_proposals()[0:25]
    comp.add_toc(top25)

    top25_topic = toc.GenericToc("Top25_Topic_TOC", "Thematic Area")
    top25_topic.proposals = top25.proposals
    comp.add_toc(top25_topic)

    with open(top13_data_file) as f:
        top13_data = f.read().splitlines()
        top13 = toc.ListToc("Top_13")
        top13.proposal_formatter = proposal_formatter
        top13.proposals = [comp.proposals[k] for k in top13_data if k in comp.proposals]
        comp.add_toc(top13)

    comp.add_toc(
        toc.MultiLevelToc(
            "Geographic_TOC",
            [
                "Future Work #1 Location",
                "Future Work #2 Location",
                "Future Work #3 Location",
                "Future Work #4 Location",
                "Future Work #5 Location",
                "Current Work #1 Location",
                "Current Work #2 Location",
                "Current Work #3 Location",
                "Current Work #4 Location",
                "Current Work #5 Location",
            ],
            [
                competition.LocationCombiner.REGION,
                competition.LocationCombiner.SUBREGION,
                competition.LocationCombiner.COUNTRY,
                competition.LocationCombiner.STATE,
            ],
        )
    )

    comp.process_tocs()

    if tdc_config_dir is not None:
        tdc.AllProposals(comp).generate(tdc_config_dir)
        tdc.ValidProposals(comp, "Valid", "Valid").generate(tdc_config_dir)
        tdc.Columns(comp).generate(tdc_config_dir)
        tdc.ProcessedCollection(comp).generate(tdc_config_dir)

    my_wiki = wiki.WikiSession(
        config.username, config.password, comp.name, config.wiki_url
    )
    my_wiki.collection_only = collection_only
    my_wiki.upload_collection(comp)
    my_wiki.upload_attachments(attachments.attachments)


if __name__ == "__main__":
    main()
