#!/bin/bash

# Copyright (C) 2017, 2019, 2020  Open Tech Strategies, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

DATA_DIR="${1}"

if [ "${DATA_DIR}" = "" ]; then
  echo "ERROR: DATA_DIRECTORY argument required."
  echo ""
  echo "Usage: '${0} DATA_DIRECTORY'"
  echo ""
  echo "(DATA_DIRECTORY is where all the .csv files are.)"
  echo ""
  exit 1
fi

# Make sure we have python3
python3 -V > /dev/null 2>&1 || { echo "python3 required, aborting" ; exit 1; }

OUTPUT_CSV="${DATA_DIR}/100Change2020/tdcconfig/etl-processed.csv"

if [ ! -f "$OUTPUT_CSV" ] ; then
  echo "ERROR: $OUTPUT_CSV doesn't exist yet"
  echo ""
  echo "You probably need to run the etl pipeline in ../100Change2020"
  exit 1
fi

echo "Creating wiki..."
# Not really doing any composing or uploading, not really.  But this keeps
# it in line with the naming convention of other, more complete, competitions.
./compose-and-upload --proposals-csv="${OUTPUT_CSV}"
echo "Done creating wiki."
