#!/bin/bash

# Copyright (C) 2017, 2019, 2020  Open Tech Strategies, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

SCRIPT_DIR=`dirname "$BASH_SOURCE"`
COMMON_SCRIPT_DIR="${SCRIPT_DIR}/../../../etl/common/deploy"
source "${COMMON_SCRIPT_DIR}/utils"
source "${COMMON_SCRIPT_DIR}/init"

COMPETITION="LoneStar2020"
LFC_DIR=`dirname "${0}"`
DATA_DIR="${BASE_DATA_DIR}/${COMPETITION}"

# Make sure we have python3
python3 -V > /dev/null 2>&1 || { echo "python3 required, aborting" ; exit 1; }

command -v xlsx2csv 2>&1 >> /dev/null || { echo >&2 "xlsx2csv required but it's not available.  Aborting."; exit 1; }

PROPOSALS_CSV="LSP_Registration_Application_data.csv"
BASE_ATTACHMENTS="LSP_Registration_Application_data.zip"
ATTACHMENTS_DIR="${DATA_DIR}/attachments/"
JUDGE_EVALUATION_CSV="LSP_Peer_Review_Data.csv"
EXPERT_PANEL_EVALUATION_CSV="Shane Eggerman - LSP_Evaluation_Panel_Data.csv"
LFC_ANALYSIS_PAGES="lfc_analysis_proposals.dat"
CORRECTION_FILE="OTS_Corrections.csv"
FINANCIAL_DATA="FinancialTablesForWiki.xlsx"
FINANCIAL_DATA_DAT="FinancialTablesForWiki.dat"
FINANCIAL_SHEETS_DIR="${DATA_DIR}/financial-sheets/"
TMP_ATTACHMENTS_DIR="${DATA_DIR}/tmpattachments"
TDC_CONFIG_DIR="${DATA_DIR}/tdcconfig"
RUNNER="${LFC_DIR}"/compose-and-upload

if [ ! -d "${DATA_DIR}" ] ; then
  echo "Stage 0: Setting up data directory..."

  if [ "${OTS_DIR}" = "" ] ; then
    echo "ERROR: \$OTS_DIR is not set up"
    echo ""
    echo "See bureaucracy/onboarding about setting the OTS_DIR environment variable up"
    exit 1
  fi

  ENCRYPTED_DIR="${OTS_DIR}/clients/lever-for-change/torque-sites/${COMPETITION}/data/bigdata"
  if [ ! -d "${ENCRYPTED_DIR}" ] ; then
    echo "ERROR: it looks like your encrypted dir isn't checked out"
    echo ""
    echo "It was expected to be in:"
    echo "  $ENCRYPTED_DIR"
    echo ""
    echo "You will need to check out the subversion torque-sites data, and then"
    echo "run get-bigdata from ${OTS_DIR}/clients/lever-for-change/torque-sites/${COMPETITION}/data/"
    exit 1
  fi

  mkdir -p $DATA_DIR
  echo "Decrypting..."

  decrypt "${DATA_DIR}/${BASE_ATTACHMENTS}" "${ENCRYPTED_DIR}/${BASE_ATTACHMENTS}.gpg" "${GPG_PASSPHRASE}"
  decrypt "${DATA_DIR}/${JUDGE_EVALUATION_CSV}" "${ENCRYPTED_DIR}/${JUDGE_EVALUATION_CSV}.gpg" "${GPG_PASSPHRASE}"
  decrypt "${DATA_DIR}/${EXPERT_PANEL_EVALUATION_CSV}" "${ENCRYPTED_DIR}/${EXPERT_PANEL_EVALUATION_CSV}.gpg" "${GPG_PASSPHRASE}"
  decrypt "${DATA_DIR}/${LFC_ANALYSIS_PAGES}" "${ENCRYPTED_DIR}/${LFC_ANALYSIS_PAGES}.gpg" "${GPG_PASSPHRASE}"
  decrypt "${DATA_DIR}/${CORRECTION_FILE}" "${ENCRYPTED_DIR}/${CORRECTION_FILE}.gpg" "${GPG_PASSPHRASE}"
  decrypt "${DATA_DIR}/${FINANCIAL_DATA}" "${ENCRYPTED_DIR}/${FINANCIAL_DATA}.gpg" "${GPG_PASSPHRASE}"
  decrypt "${DATA_DIR}/${FINANCIAL_DATA_DAT}" "${ENCRYPTED_DIR}/${FINANCIAL_DATA_DAT}.gpg" "${GPG_PASSPHRASE}"

  mkdir -p ${TDC_CONFIG_DIR}

  echo "Setting up attachments..."
  mkdir -p $TMP_ATTACHMENTS_DIR
  unzip -d ${TMP_ATTACHMENTS_DIR} ${DATA_DIR}/${BASE_ATTACHMENTS}
  mv "${TMP_ATTACHMENTS_DIR}/${PROPOSALS_CSV}" $DATA_DIR
  mv "${TMP_ATTACHMENTS_DIR}/Valid" $ATTACHMENTS_DIR

  # Clean up large zips to save disk space
  rm ${DATA_DIR}/${BASE_ATTACHMENTS}
  rm -rf ${DATA_DIR}/${TMP_ATTACHMENTS_DIR}

  mkdir -p "${FINANCIAL_SHEETS_DIR}"
  cat "${DATA_DIR}/${FINANCIAL_DATA_DAT}" | while read APP_NUMBER ; do
    xlsx2csv "$DATA_DIR/$FINANCIAL_DATA" -n $APP_NUMBER > ${FINANCIAL_SHEETS_DIR}/$APP_NUMBER.csv
  done
fi

if ! echo "3645633f683f603178c17a8b682d5ed0405d340f  $DATA_DIR/$PROPOSALS_CSV" | sha1sum -c &> /dev/null ; then
  echo "ERROR: SHA of PROPOSALS_CSV did not match expectation!"
  echo "This means that we most likely got a new file, which may have the old"
  echo "errors in it (specifically the organization proposal 829)."
  echo "If we got a new file and there are no further errors, you"
  echo "can remove this check from torque-refresh!  If not, please"
  echo "make adjustments in a new file and update the sha."
  exit 1
fi

mkdir -p $TDC_CONFIG_DIR

${RUNNER} --proposals-csv="${DATA_DIR}/${PROPOSALS_CSV}" \
          --judge-evaluation-csv="${DATA_DIR}/${JUDGE_EVALUATION_CSV}" \
          --expert-panel-evaluation-csv="${DATA_DIR}/${EXPERT_PANEL_EVALUATION_CSV}" \
          --lfc-analysis-pages="${DATA_DIR}/${LFC_ANALYSIS_PAGES}" \
          --correction-file="${DATA_DIR}/${CORRECTION_FILE}" \
          --attachments-dir=${ATTACHMENTS_DIR} \
          --financial-sheets-dir=${FINANCIAL_SHEETS_DIR} \
          $PARE \
          $CSV_ONLY \
          --tdc-config-dir="${TDC_CONFIG_DIR}"
if [ $? -ne 0 ]; then
		echo Failure!
		exit 1
fi

echo "Done creating wiki."
