#!/bin/bash

# Copyright (C) 2017, 2019, 2020  Open Tech Strategies, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

CSV_ONLY=""
PARE=""
while getopts "cp:" opt; do
  case $opt in
    c) CSV_ONLY="--csv-only" ;;
    p) PARE="--pare=$OPTARG" ;;
  esac
done
shift $((OPTIND -1))

COMPETITION="RacialEquity2030"
LFC_DIR=`dirname "${0}"`
BASE_DATA_DIR="${1}"

if [ "${BASE_DATA_DIR}" = "" ]; then
  echo "ERROR: BASE_DATA_DIRECTORY argument required."
  echo ""
  echo "Usage: '${0} [-c] [-p arg] BASE_DATA_DIRECTORY'"
  echo ""
  echo "Options:"
  echo ""
  echo "  -c                  Uploads CSV only.  Skips creating pages and"
  echo "                      uploading attachments."
  echo "  -p <arg>            If ARG is a number, pares by factor of ARG. If"
  echo "                      ARG begins with +, then ARG is a comma separated"
  echo "                      list of keys to include.  If ARG begins with @,"
  echo "                      then ARG is a file with a newline separated list"
  echo "                      of keys to include."
  echo ""
  echo "BASE_DATA_DIRECTORY/$COMPETITION is where all the work is done."
  echo ""
  exit 1
fi

DATA_DIR="${BASE_DATA_DIR}/${COMPETITION}"

# Make sure we have python3
python3 -V > /dev/null 2>&1 || { echo "python3 required, aborting" ; exit 1; }

PROPOSALS_CSV="RE2020_Registration_Application_2021-03-24_06-29-20.csv"
BASE_ATTACHMENTS="RE2020_Registration_Application_exports_2021-03-24_08-08-31.zip"

TMP_ATTACHMENTS_DIR="${DATA_DIR}/tmpattachments"
TDC_CONFIG_DIR="${DATA_DIR}/tdcconfig"
RUNNER="${LFC_DIR}"/compose-and-upload

decrypt () {
  local output_location=${1}
  local encrypted_location=${2}
  local passphrase=${3}

  if [ -z "${passphrase}" ]; then
    echo 'NO PASSPHRASE'
    gpg -o ${output_location} --decrypt ${encrypted_location} || exit 1
  else
    echo 'PASSPHRASE'
    gpg --batch --passphrase "${passphrase}" -o ${output_location} --decrypt ${encrypted_location} || exit 1
  fi
}

if [ ! -d "${DATA_DIR}" ] ; then
  echo "Stage 0: Setting up data directory..."

  if [ "${OTS_DIR}" = "" ] ; then
    echo "ERROR: \$OTS_DIR is not set up"
    echo ""
    echo "See bureaucracy/onboarding about setting the OTS_DIR environment variable up"
    exit 1
  fi

  ENCRYPTED_DIR="${OTS_DIR}/clients/lever-for-change/torque-sites/${COMPETITION}/data/bigdata"
  if [ ! -d "${ENCRYPTED_DIR}" ] ; then
    echo "ERROR: it looks like your encrypted dir isn't checked out"
    echo ""
    echo "It was expected to be in:"
    echo "  $ENCRYPTED_DIR"
    echo ""
    echo "You will need to check out the subversion torque-sites data, and then"
    echo "run get-bigdata from ${OTS_DIR}/clients/lever-for-change/torque-sites/${COMPETITION}/data/"
    exit 1
  fi

  mkdir -p $DATA_DIR
  echo "Decrypting..."

  decrypt "${DATA_DIR}/${BASE_ATTACHMENTS}" "${ENCRYPTED_DIR}/${BASE_ATTACHMENTS}.gpg" "${GPG_PASSPHRASE}"

  mkdir -p ${TDC_CONFIG_DIR}

  echo "Setting up attachments..."
  mkdir -p $TMP_ATTACHMENTS_DIR
  unzip -d ${TMP_ATTACHMENTS_DIR} ${DATA_DIR}/${BASE_ATTACHMENTS}
  mv "${TMP_ATTACHMENTS_DIR}/*/${PROPOSALS_CSV}" $DATA_DIR
  mv "${TMP_ATTACHMENTS_DIR}/*/Valid" $ATTACHMENTS_DIR

  # Clean up large zips to save disk space
  rm ${DATA_DIR}/${BASE_ATTACHMENTS}
  rm -rf ${DATA_DIR}/${TMP_ATTACHMENTS_DIR}
fi

if ! echo "eff94580e150286313a32d3d12c1ec659851b62c  $DATA_DIR/$PROPOSALS_CSV" | sha1sum -c &> /dev/null ; then
  echo "ERROR: SHA of PROPOSALS_CSV did not match expectation!"
  echo "This means that we most likely got a new file, which may have the old"
  echo "errors in it (specifically the organization proposal 829)."
  echo "If we got a new file and there are no further errors, you"
  echo "can remove this check from torque-refresh!  If not, please"
  echo "make adjustments in a new file and update the sha."
  exit 1
fi

mkdir -p $TDC_CONFIG_DIR

${RUNNER} --proposals-csv="${DATA_DIR}/${PROPOSALS_CSV}" \
          --attachments-dir=${ATTACHMENTS_DIR} \
          $PARE \
          $CSV_ONLY \
          --tdc-config-dir="${TDC_CONFIG_DIR}"
if [ $? -ne 0 ]; then
		echo Failure!
		exit 1
fi

echo "Done creating wiki."
