#!/bin/bash

# See the README.md about the general information, but the salient
# point is that this was last run on May 20, 2021, and so may
# be out of date.  For the most part, everything is configured
# in the top level variables here at the top.  The rest of the
# script is relatively generic.

# Also, the script hasn't been tested end to end, as it was run
# piecemeal as it was created.  But it should work!

COMPETITIONS="100Change2017 100Change2020 Climate2030 ECW2020 EO2020 GlobalView LLIIA2020 LoneStar2020 RacialEquity2030 Democracy22"
BASE="simplebook simplesaml torque"
DIRECTORIES="$COMPETITIONS simplesaml simplebook torque"
TORQUE_SITES_DIRECTORY="/tmp/torque-sites"
TORQUE_SITES_SHA="main"
PG_DATABASES="100Change2017 torque"
MYSQL_DATABASES="100Change2020 Climate2030 ECW2020 EO2020 GlobalView LLIIA2020 LoneStar2020 RacialEquity2030 Democracy22 simplesamlphp"
PRODUCTION_SERVER="torque.leverforchange.org"
TARGET_SERVER="wiki.opentechstrategies.com"

# Checkout torque-sites to a place we can mutate
mkdir -p $TORQUE_SITES_DIRECTORY
git -C $TORQUE_SITES_DIRECTORY clone https://github.com/OpenTechStrategies/torque-sites .
git -C $TORQUE_SITES_DIRECTORY checkout $TORQUE_SITES_SHA

echo "This will blow away all the databases related to torque on $TARGET_SERVER and all the files in the installed directories"
echo -n "Please hit enter to continue"
read

for db in $MYSQL_DATABASES ; do
  ssh $TARGET_SERVER "sudo mysql -e 'DROP DATABASE $db'"
done

for db in $PG_DATABASES ; do
  ssh $TARGET_SERVER "sudo -u postgres psql -c 'DROP DATABASE \"$db\"'"
done

for directory in $DIRECTORIES ; do
  ssh $TARGET_SERVER "sudo rm -rf ~deploy/$directory"
done

# Install the opass secrets, set the production host to the target, and run ansible
(
  cd $TORQUE_SITES_DIRECTORY

  opass show clients/lever-for-change/torque/ansible/prod > base/torque/ansible/inv/prod/group_vars/all/secret
  opass show clients/lever-for-change/simplesaml/ansible/prod > base/simplesaml/ansible/inv/prod/group_vars/all/secret
  for base in $BASE ; do
    sed -i -e "s/$PRODUCTION_SERVER/$TARGET_SERVER/" base/$base/ansible/inv/prod/hosts
    (
      cd base/$base/ansible
      ansible-playbook -i inv/prod $base.yml
    )
  done

  for comp in $COMPETITIONS ; do
    opass show clients/lever-for-change/torque-sites/$comp/ansible/prod > competitions/$comp/ansible/inv/prod/group_vars/all/secret
    sed -i -e "s/$PRODUCTION_SERVER/$TARGET_SERVER/" competitions/$comp/ansible/inv/prod/hosts
    (
      cd competitions/$comp/ansible
      ansible-playbook -i inv/prod $comp.yml
    )
  done

)

for db in $MYSQL_DATABASES ; do
  ssh $PRODUCTION_SERVER "sudo mysqldump $db" | ssh $TARGET_SERVER "sudo mysql $db"
done

for db in $PG_DATABASES ; do
  ssh $PRODUCTION_SERVER "sudo -u postgres pg_dump -c $db" | ssh $TARGET_SERVER "sudo -u postgres psql $db"
done

for dir in $DIRECTORIES ; do
  ssh $PRODUCTION_SERVER "sudo tar -C ~deploy/$dir -cpvz ." | ssh $TARGET_SERVER "sudo tar -C ~deploy/$dir -zpx"
done
