#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2017, 2019, 2020 Open Tech Strategies, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

__doc__ = """\
Compose all of the Lever for Change Equality Can't Wait 2020 Proposal CSV files.

Usage:

  $ compose-and-upload \\
       --proposals-csv=PROPOSALS_CSV \\
       --attachments-dir=ATTACHMENTS_DIR \\
       --judge-evaluation-csv=JUDGE_EVALUATION_CSV \\
       --expert-panel-evaluation-csv=EXPERT_PANEL_EVALUATION_CSV \\
       --application-data=APPLICATION_DATA_CSV \\
       --tdc-config-dir=TDC_CONFIG_DIR \\
       --pare=PARE \\
       --csv-only

Command-line options:
  --proposals-csv FILE            FILE is a CSV file representing the bulk
                                  of the proposal information

  --attachments-dir DIR           DIR is a directory for compose-csvs to look in for what attachments
                                  will be uploaded to the torque wiki.  It needs to have subdirectories
                                  by proposal number.

  --tdc-config-dir DIR            DIR is the location for files that are the base configuration files
                                  needed by TorqueDataConnect, and can be optionally, manually, put on
                                  the torque wiki.  We don't automatically do that because we want to
                                  overwrite the configuration out there.

  --judge-evaluation-csv FILE     FILE is a CSV file with a many to one relationshp
                                  between judges and the proposals they evaluated,
                                  with the extra data being their evaluation

  --expert-panel-evaluation-csv FILE    FILE is a CSV file with a row for each proposal
                                  that includes the rank and scoring for the expert panel
                                  review, but none of the comments.

  --application-data FILE         FILE is a CSV file that provides the Theme and the Region
                                  for different proposals.  There are other columns in the
                                  sheet, but these are the only ones of use to the ETL pipeline.

  --financial-sheets-dir DIR      DIR is the location for financial data csvs in a very specific
                                  format that's handled by FinancialDataAdder.  They get
                                  transformed into json and then displayed on ont he LFC Analysis pages.

  --pare ARG                      If ARG is a number, reduce the number of items to 1/ARG.  If
                                  ARG begins with +, then ARG is a comma separated list of
                                  keys to include.  If ARG begins with @, then ARG is a
                                  file with a list of keys to include.  For both + and @,
                                  the list of keys will be limited to only the ones provided.

  --csv-only                      Only upload the created CSV file.  Don't upload attachments or
                                  create wiki pages.  For use to speed up process when wiki has been
                                  created already.
"""

from etl import competition, wiki, toc, tdc
import config
import getopt
import sys
import os
import csv


class LFCAnalysisAdder(competition.InformationAdder):
    """Adds the columns for the LFC Analysis, all empty because these
    cells are there to be edited upon later"""

    def column_names(self):
        return [
            "LFC Analysis: Recommendation",
            "LFC Analysis: Short Description",
            "LFC Analysis: Overview",
            "LFC Analysis: Funder Relationship History",
            "LFC Analysis: Transformative Summary",
            "LFC Analysis: Equitable Summary",
            "LFC Analysis: Innovative Summary",
            "LFC Analysis: Feasible Summary",
            "LFC Analysis: Strength of Approach",
            "LFC Analysis: Risks and Challenges",
            "LFC Analysis: Strategic Approach and WPI Indicators",
            "LFC Analysis: Internet Scan",
            "LFC Analysis: Diversity, Equity and Inclusion",
            "LFC Analysis: Observations",
            "LFC Analysis: Financial Overview",
            "LFC Analysis: Funding Overview",
        ]

    def cell(self, proposal, column_name):
        return ""


class ApplicationDataAdder(competition.InformationAdder):
    """Very specific adder that takes a spreadsheet with some extra
    application data, keyed by Application #, and adds it to the
    final data set."""

    def __init__(self, application_data_csv):
        self.data = {}

        proposal_financial_data = {}

        reader = csv.reader(
            open(application_data_csv),
            delimiter=",",
            quotechar='"',
            lineterminator="\n",
        )

        header = next(reader)

        review_num_col = header.index("Review #")
        theme_col = header.index("Theme")
        region_col = header.index("Region")

        for row in reader:
            theme = row[theme_col]

            # Request from client
            if theme == "Other (e.g xyz)":
                theme = "Other"

            self.data[row[review_num_col]] = {
                "Application Data Theme": theme,
                "Application Data Region": row[region_col],
            }

    def column_names(self):
        return ["Application Data Theme", "Application Data Region"]

    def cell(self, proposal, column_name):
        return self.data.get(proposal.key(), {}).get(column_name, "")


def main():
    """Compose the LFC input and emit it as html-ized csv."""
    try:
        opts, args = getopt.getopt(
            sys.argv[1:],
            "",
            [
                "proposals-csv=",
                "tdc-config-dir=",
                "judge-evaluation-csv=",
                "expert-panel-evaluation-csv=",
                "application-data=",
                "financial-sheets-dir=",
                "attachments-dir=",
                "pare=",
                "csv-only",
            ],
        )
    except getopt.GetoptError as err:
        sys.stderr.write("ERROR: '%s'\n" % err)
        sys.exit(2)

    proposals_csv = None
    attachments_dir = None
    tdc_config_dir = None
    judge_evaluation_csv = None
    expert_panel_evaluation_csv = None
    application_data_csv = None
    financial_sheets_dir = None
    pare = None
    csv_only = False
    for o, a in opts:
        if o == "--proposals-csv":
            proposals_csv = a
        elif o == "--pare":
            pare = a
        elif o == "--csv-only":
            csv_only = True
        elif o == "--tdc-config-dir":
            tdc_config_dir = a
        elif o == "--judge-evaluation-csv":
            judge_evaluation_csv = a
        elif o == "--expert-panel-evaluation-csv":
            expert_panel_evaluation_csv = a
        elif o == "--application-data":
            application_data_csv = a
        elif o == "--financial-sheets-dir":
            financial_sheets_dir = a
        elif o == "--attachments-dir":
            attachments_dir = a
        else:
            sys.stderr.write("ERROR: unrecognized option '%s'\n" % o)
            sys.exit(2)

    if proposals_csv is None:
        sys.stderr.write("ERROR: need --proposals-csv option.\n\n")
        sys.stderr.write(__doc__)
        sys.exit(1)

    comp = competition.Competition(proposals_csv, "ECW2020", "Application #", pare)

    fix_cell_processor = competition.FixCellProcessor()
    comp.process_all_cells_special(fix_cell_processor)
    fix_cell_processor.report()

    comp.process_cells_special(
        "Organization Name", competition.RemoveHTMLBRsProcessor()
    )
    comp.process_cells_special("Project Title", competition.RemoveHTMLBRsProcessor())

    comp.add_supplemental_information(competition.MediaWikiTitleAdder("Project Title"))
    comp.add_supplemental_information(
        competition.GlobalViewMediaWikiTitleAdder("ECW2020", "Project Title")
    )
    comp.add_supplemental_information(
        competition.StaticColumnAdder("Competition Name", "ECW2020")
    )

    comp.filter_proposals(
        competition.ColumnEqualsProposalFilter("Admin Review Status", "Not submitted")
    )
    comp.process_cells_special("Priority Populations", competition.MultiLineProcessor())
    comp.process_cells_special("Total Projected Costs", competition.NumberCommaizer())
    comp.process_cells_special("Budget data", competition.BudgetTableProcessor())

    comp.process_cells_special(
        "Annual Operating Budget",
        competition.AnnualBudgetProcessor(
            {
                competition.AnnualBudget.LESS_THAN_1_MIL: "Less than $1 Million",
                competition.AnnualBudget.BETWEEN_1_MIL_AND_5_MIL: "$1.0 to 5.0 Million",
                competition.AnnualBudget.BETWEEN_5_MIL_AND_10_MIL: "$5.1 to 10 Million",
                competition.AnnualBudget.BETWEEN_10_MIL_AND_25_MIL: "$10.1 to 25 Million",
                competition.AnnualBudget.BETWEEN_25_MIL_AND_50_MIL: "$25.1 to 50 Million",
                competition.AnnualBudget.BETWEEN_50_MIL_AND_100_MIL: "$50.1 to 100 Million",
                competition.AnnualBudget.BETWEEN_100_MIL_AND_500_MIL: "$100.1 to 500 Million",
                competition.AnnualBudget.BETWEEN_500_MIL_AND_1_BIL: "$500.1 Million to $1 Billion",
                competition.AnnualBudget.MORE_THAN_1_BIL: "$1 Billion +",
            }
        ),
    )

    comp.add_supplemental_information(
        competition.EvaluationAdder(
            "Judge",
            judge_evaluation_csv,
            app_col_name="Application #",
            score_rank_normalized_col_name="OverallScoreRankNormalized",
            sum_of_scores_normalized_col_name="SumOfScoresNormalized",
            trait_col_name="Trait",
            score_normalized_col_name="TraitScoreNormalized",
            comments_col_name="TraitJudgeComment",
            comments_score_normalized_col_name="TraitScoreNormalized",
        )
    )
    comp.add_supplemental_information(
        competition.EvaluationAdder(
            "Panel",
            expert_panel_evaluation_csv,
            app_col_name="Application #",
            score_rank_normalized_col_name="OverallScoreRankNormalized",
            sum_of_scores_normalized_col_name="SumOfScoresNormalized",
            trait_col_name="Trait",
            score_normalized_col_name="TraitScoreNormalized",
            comments_col_name="TraitJudgeComment",
            comments_score_normalized_col_name="TraitScoreNormalized",
        )
    )
    comp.add_supplemental_information(LFCAnalysisAdder())

    comp.add_supplemental_information(
        competition.FinancialDataAdder(
            financial_sheets_dir,
            [
                {"name": "revenues", "text": "Revenues"},
                {"name": "expenses", "text": "Expenses (after depreciation)"},
                {
                    "name": "surplus",
                    "text": "Unrestricted surplus (after depreciation)",
                },
                {
                    "name": "surplus as percent",
                    "text": "As percent of expenses",
                    "percent": True,
                },
                {"name": "net assets", "text": "Unrestricted net assets"},
                {
                    "name": "months",
                    "text": "Months of liquid unrestricted net assets (LUNA)",
                },
                {
                    "name": "months2",
                    "text": "Months of liquid unrestricted net assets (LUNA) [2]",
                },
                {
                    "name": "months3",
                    "text": "Months of liquid unrestricted net assets (LUNA) [3]",
                },
                {
                    "name": "magnitude",
                    "text": "Magnitude of surplus / (deficits) (change in unrestricted net assets / average expenses over time period)",
                    "percent": True,
                },
                {
                    "name": "magnitude3",
                    "text": "Magnitude of surplus / (deficits) (change in unrestricted net assets / average expenses over time period) [3]",
                    "percent": True,
                },
                {
                    "name": "magnitude4",
                    "text": "Magnitude of surplus / (deficits) (change in unrestricted net assets / average expenses over time period) [4]",
                    "percent": True,
                },
            ],
        )
    )

    comp.add_supplemental_information(LFCAnalysisAdder())

    attachments = competition.BasicAttachments(
        comp.sorted_proposal_keys, attachments_dir
    )
    comp.add_supplemental_information(attachments)
    comp.add_supplemental_information(ApplicationDataAdder(application_data_csv))
    comp.sort("Panel Overall Score Rank Normalized", True)

    list_toc = toc.ListToc("All_Proposals")
    list_toc.proposal_formatter = toc.WikiTableTocProposalFormatter(
        [
            {
                "name": "Organization Name",
                "heading": "Organization",
            },
            {
                "name": "Project Title",
                "heading": "Title",
                "link": True,
            },
            {
                "name": "Application #",
                "heading": "ID #",
                "right_aligned": True,
            },
            {
                "name": "Panel Overall Score Rank Normalized",
                "heading": "Panel Rank",
                "right_aligned": True,
            },
            {
                "name": "Judge Overall Score Rank Normalized",
                "heading": "Peer Rank",
                "right_aligned": True,
            },
        ]
    )
    comp.add_toc(list_toc)

    comp.add_toc(toc.GenericMultiLineToc("Populations", "Priority Populations"))
    comp.add_toc(toc.GenericToc("Themes", "Application Data Theme"))
    comp.add_toc(toc.GenericToc("Regions", "Application Data Region"))

    comp.add_toc(toc.AnnualBudgetToc("Annual Operating Budget"))

    comp.add_toc(
        toc.GenericToc(
            "Number_of_Employees",
            "Number of Employees",
            [
                "Fewer than 10 Full-time Employees",
                "10 to 25 Full-time Employees",
                "26 to 50 Full-time Employees",
                "51 to 100 Full-time Employees",
                "101 to 300 Full-time Employees",
                "301 to 500 Full-time Employees",
                "501 to 1,000 Full-time Employees",
                "1,000+ Full-time Employees",
            ],
        )
    )

    comp.add_toc(
        toc.GeographicToc(
            "Current_Work_Locations",
            [
                [
                    "Location of Current Work #1 Country",
                    "Location of Current Work #1 State /Province",
                ],
                [
                    "Location of Current Work #2 Country",
                    "Location of Current Work #2 State /Province",
                ],
                [
                    "Location of Current Work #3 Country",
                    "Location of Current Work #3 State /Province",
                ],
                [
                    "Location of Current Work #4 Country",
                    "Location of Current Work #4 State /Province",
                ],
                [
                    "Location of Current Work #5 Country",
                    "Location of Current Work #5 State /Province",
                ],
            ],
        )
    )

    comp.add_toc(
        toc.GeographicToc(
            "Future_Work_Locations",
            [
                [
                    "Location of Future Work #1 Country",
                    "Location of Future Work #1 State / Province",
                ],
                [
                    "Location of Future Work #2 Country",
                    "Location of Future Work #2 State /Province",
                ],
                [
                    "Location of Future Work #3 Country",
                    "Location of Future Work #3 State /Province",
                ],
                [
                    "Location of Future Work #4 Country",
                    "Location of Future Work #4 State /Province",
                ],
                [
                    "Location of Future Work #5 Country",
                    "Location of Future Work #5 State /Province",
                ],
            ],
        )
    )

    comp.process_tocs()

    if tdc_config_dir is not None:
        tdc.AllProposals(comp).generate(tdc_config_dir)
        tdc.ValidProposals(comp, "Admin Review Status", "Valid").generate(
            tdc_config_dir
        )
        tdc.AllColumns(comp).generate(tdc_config_dir)
        tdc.ProcessedSpreadsheet(comp).generate(tdc_config_dir)

    my_wiki = wiki.WikiSession(
        config.username, config.password, comp.name, config.wiki_url
    )
    my_wiki.csv_only = csv_only
    my_wiki.upload_sheet(comp)
    my_wiki.upload_attachments(attachments.attachments)

    for proposal in comp.proposals.values():
        my_wiki.create_page(
            "Evaluations of %s" % proposal.cell("MediaWiki Title"),
            "{{ #tdcrender:ECW2020/id/" + proposal.key() + ".mwiki|Evaluations }}",
        )

    for key in comp.sorted_proposal_keys[0:19]:
        proposal = comp.proposals[key]
        my_wiki.create_page(
            "LFC Analysis of %s" % proposal.cell("MediaWiki Title"),
            "{{ #tdcrender:ECW2020/id/" + key + ".mwiki|LFCAnalysis }}",
            True,
        )


if __name__ == "__main__":
    main()
