#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2017, 2019, 2020 Open Tech Strategies, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

__doc__ = """\
Usage:

  $ compose-and-upload --proposals-json=PROPOSALS_JSON

Command-line options:
  --proposals-json FILE           FILE is a JSON file representing the bulk
                                  of the proposal information.  This is the json
                                  that came from 100Change2020
"""

from etl import competition, wiki, toc, tdc
import config
import getopt
import sys
import os


def main():
    """Compose the LFC input and emit it as html-ized json."""
    try:
        opts, args = getopt.getopt(
            sys.argv[1:],
            "",
            [
                "proposals-json=",
            ],
        )
    except getopt.GetoptError as err:
        sys.stderr.write("ERROR: '%s'\n" % err)
        sys.exit(2)

    proposals_json = None
    for o, a in opts:
        if o == "--proposals-json":
            proposals_json = a
        else:
            sys.stderr.write("ERROR: unrecognized option '%s'\n" % o)
            sys.exit(2)

    if proposals_json is None:
        sys.stderr.write("ERROR: need --proposals-json option.\n\n")
        sys.stderr.write(__doc__)
        sys.exit(1)

    comp = competition.JsonBasedCompetition(proposals_json, "LFC100Change2020", "Application #")

    my_wiki = wiki.WikiSession(
        config.username, config.password, comp.name, config.wiki_url
    )
    my_wiki.create_pages(comp)


if __name__ == "__main__":
    main()
